sudo: required
services:
  - docker

before_install:
  - docker build -t saveup/saveup-frontend .
  - docker build -t tests -f Dockerfile.dev .
script:
  - docker run tests npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "SAVEUP-FRONTEND"
  env: "Saveupfrontend-env"
  bucket_name: "elasticbeanstalk-us-east-2-855433857104"
  bucket_path: "saveupfrontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
